#!/usr/bin/env python3
"""Generate the UAX #50 vertical orientation table for YueduCoreTextTypography.

Reads `VerticalOrientation.txt` from the Unicode Character Database at a pinned
version and writes `Sources/YueduCoreTextTypography/VerticalOrientationTable.swift`:
sorted, merged ranges for `U`, `Tu` and `Tr`. Everything else is `R`, the data
file's `@missing` default. A manifest beside this script records the version and
the SHA-256 of the input and the output, so a rerun proves the table is unchanged.

Usage:
  scripts/vertical_orientation.py [--source FILE] [--check]

--source reads a local copy instead of downloading; --check fails when the
written table would differ from the committed one.
"""

import argparse
import hashlib
import json
import pathlib
import subprocess
import sys

VERSION = "18.0.0"
URL = f"https://www.unicode.org/Public/{VERSION}/ucd/VerticalOrientation.txt"
ROOT = pathlib.Path(__file__).resolve().parent.parent
OUTPUT = ROOT / "Sources" / "YueduCoreTextTypography" / "VerticalOrientationTable.swift"
MANIFEST = pathlib.Path(__file__).resolve().parent / "vertical_orientation.manifest.json"
CODES = {"U": "upright", "Tu": "transformedUpright", "Tr": "transformedRotated"}


def read_source(path):
    if path:
        return pathlib.Path(path).read_bytes()
    # curl uses the system's certificate store; a python.org Python has none of its own.
    return subprocess.run(["curl", "-sfL", "--max-time", "60", URL], check=True,
                          capture_output=True).stdout


def parse(data):
    text = data.decode("utf-8")
    first = text.splitlines()[0]
    if f"VerticalOrientation-{VERSION}.txt" not in first:
        sys.exit(f"expected VerticalOrientation-{VERSION}.txt, got: {first}")
    if "# @missing: 0000..10FFFF; R" not in text:
        sys.exit("the data file no longer declares R as its default; the table assumes it")
    ranges = []
    for raw in text.splitlines():
        line = raw.split("#", 1)[0].strip()
        if not line:
            continue
        codes, value = (part.strip() for part in line.split(";"))
        if value not in ("U", "Tu", "Tr", "R"):
            sys.exit(f"unknown Vertical_Orientation value {value!r} in: {raw}")
        if ".." in codes:
            lower, upper = (int(part, 16) for part in codes.split(".."))
        else:
            lower = upper = int(codes, 16)
        ranges.append((lower, upper, value))
    ranges.sort()
    merged = []
    for lower, upper, value in ranges:
        if value == "R":
            continue
        if merged and merged[-1][2] == value and merged[-1][1] + 1 == lower:
            merged[-1] = (merged[-1][0], upper, value)
        else:
            merged.append((lower, upper, value))
    for (_, upper, _), (lower, _, _) in zip(merged, merged[1:]):
        if lower <= upper:
            sys.exit(f"overlapping ranges near U+{lower:04X}")
    return merged


def render(ranges, source_sha):
    lines = [
        "// Generated by scripts/vertical_orientation.py from the Unicode Character",
        f"// Database VerticalOrientation-{VERSION}.txt (SHA-256 {source_sha}).",
        "// Do not edit by hand. Unicode data: Copyright © 1991-2026 Unicode, Inc.,",
        "// under the Unicode License v3; see NOTICE.",
        "",
        "extension VerticalOrientation {",
        f"    /// The UCD version the table was generated from.",
        f"    public static let unicodeVersion = \"{VERSION}\"",
        "",
        "    /// Sorted, non-overlapping code point ranges that are not `R`.",
        "    static let ranges: [(lower: UInt32, upper: UInt32, value: VerticalOrientation)] = [",
    ]
    for lower, upper, value in ranges:
        lines.append(f"        (0x{lower:04X}, 0x{upper:04X}, .{CODES[value]}),")
    lines += ["    ]", "}", ""]
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--source")
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()

    data = read_source(args.source)
    source_sha = hashlib.sha256(data).hexdigest()
    swift = render(parse(data), source_sha)
    output_sha = hashlib.sha256(swift.encode("utf-8")).hexdigest()
    if args.check:
        current = OUTPUT.read_text(encoding="utf-8") if OUTPUT.exists() else ""
        if current != swift:
            sys.exit(f"{OUTPUT} differs from what VerticalOrientation-{VERSION}.txt generates")
        print("table matches")
        return
    OUTPUT.write_text(swift, encoding="utf-8")
    MANIFEST.write_text(json.dumps({
        "unicodeVersion": VERSION,
        "source": URL,
        "sourceSHA256": source_sha,
        "output": str(OUTPUT.relative_to(ROOT)),
        "outputSHA256": output_sha,
    }, indent=2) + "\n", encoding="utf-8")
    print(f"wrote {OUTPUT.relative_to(ROOT)}: {swift.count(chr(10))} lines")


if __name__ == "__main__":
    main()
